[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.10.0",
    "setuptools-git-versioning<2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true
